### ISSUE TITLE
Update `eslint-config-wordpress` to version `1.0.0`

### ISSUE THREAD

**Issue by ntwb** [electric-eloquence/fepper-wordpress#3]
Hi,

Thanks for using, or rather trying to use [eslint-config-wordpress](https://github.com/ntwb/eslint-config-wordpress) 😄 

I'v just released version 1.0.0:
• https://www.npmjs.com/package/eslint-config-wordpress
• https://github.com/ntwb/eslint-config-wordpress/releases/tag/1.0.0

The key change is to relax the configuration significantly, full details and a roadmap going forward can be read here: 
• https://github.com/ntwb/eslint-config-wordpress/issues/8

As the 1.0.0 config is the same as WordPress' core's current `jshintrc` and can be used as a "drop in" replacement for JSHint this should hopefully allow you to re-enable your ESlint config here:
• https://github.com/electric-eloquence/fepper-wordpress/blob/master/app/tasker.js#L89-L95

**Comment by e2tha-e** [comment]
Linting has been moved out of core into extensions, the one particular to ESLint being https://www.npmjs.com/package/fp-eslint

Users can determine their own configs with this extension. Closing this issue.
